### ISSUE TITLE
Run Kubernetes pods in Kerla on Firecracker

### ISSUE THREAD

**Issue by nuta** [nuta/kerla#51]
Namely, write documentation and implement missing features to make following manifest work:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  runtimeClassName: kerla
  containers:
  - name: nginx
    image: nginx
```

See https://kubernetes.io/docs/concepts/containers/runtime-class/
